#!/usr/bin/env bash
#
# build_demo.sh — populate a throwaway demo database with synthetic footage.
#
# WHY THIS EXISTS: a real Hushai deployment holds recordings of real people. Nothing from a
# working install can be screenshotted, demoed, or shared. This script builds a parallel
# `hushai_demo` database whose every frame comes from a public-domain photograph and whose
# every word is synthesized by `say` — so the UI can be shown to anyone, and the README's
# screenshots can be regenerated by anyone, without exposing a single real recording.
#
# Three fictional cameras, each with its own perception lane and a scripted conversation:
#   Front Door   — a public-domain NASA portrait (face detect + re-identification)
#   Driveway     — a public-domain street photo carrying plate EMD774 (ALPR + object lane)
#   Back Garden  — a second, distinct public-domain portrait (so re-ID mints two people)
#
# Media provenance (all public domain, same sources the eval fixtures use — see
# local_dev/fetch_eval_clips.sh and hushai-eval/README.md):
#   * Judith A. Resnik official NASA portrait
#   * Sally Ride (1984), NASA
#   * "Cars in traffic in Auckland, New Zealand" — released to the public domain
#   * Peugeot iOn in front of wind turbines — public domain
#
# USAGE — bring a stack up against the demo database FIRST, then run this:
#
#   createdb hushai_demo
#   DATABASE_URL="postgres://$USER@localhost:5432/hushai_demo" \
#   BLOB_DIR="$PWD/local_dev/.demo_work/blobs" \
#   VISION_MOTION_SKIP_ENABLED=false \
#     ./local_dev/run_stack.sh
#
#   ./local_dev/build_demo.sh
#
# VISION_MOTION_SKIP_ENABLED=false is required, not optional: the skip-static motion gate is
# stateful per camera, so re-injecting the same clip would be skipped from the second slot
# onwards and most of the timeline would have no detections behind it.
#
# Knobs (all optional):
#   DEMO_DB_URL      default postgres://$USER@localhost:5432/hushai_demo  (MUST end in `_demo`)
#   DEMO_BACKEND     default http://localhost:8080
#   DEVICE_TOKEN     bearer for ingest + admin (falls back to ./.env, then dev-secret-token)
#   DEMO_DAYS        default 3    how many days back to spread footage over
#   DEMO_SLOTS       default 2    injections per camera per day
#   DEMO_CLIP_SECS   default 60   length of each generated clip
#   DEMO_RESET       set to 1 to empty the demo data first (coherent rebuild)
#   DEMO_DRAIN_TIMEOUT default 3600  seconds to wait for the worker; it warns and continues
#                                    rather than failing, so a slow machine still gets a dataset
#
# AFTERWARDS: the README screenshots are captured from this dataset in two passes (the second
# needs ./local_dev/demo_live_feed.sh running). See docs/screenshots.md — don't just run
# shots.mjs once.
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by byte offset, so an edit
# mid-run makes it resume mid-line (observed: `psql "$DB_UR` + `L -tAF...: command not found`,
# which killed a 40-minute run right after the drain completed).
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/local_dev/.demo_work"
CACHE="$WORK/cache"
CLIPDIR="$WORK/clips"
EVAL_CACHE="$ROOT/hushai-eval/.work/clip-cache"

# Default to the invoking OS user: a bare postgres://localhost/db makes libpq/sqlx resolve a
# role from the connection rather than the shell user, which fails with
# `role "anonymous" does not exist` on a stock Homebrew Postgres.
DB_URL="${DEMO_DB_URL:-postgres://${USER}@localhost:5432/hushai_demo}"
BACKEND="${DEMO_BACKEND:-http://localhost:8080}"
DAYS="${DEMO_DAYS:-3}"
SLOTS="${DEMO_SLOTS:-2}"
CLIP_SECS="${DEMO_CLIP_SECS:-60}"
FPS=25

log() { printf '[demo] %s\n' "$*"; }
die() { printf '[demo] FATAL: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------- preflight
for t in ffmpeg curl python3 psql; do
  command -v "$t" >/dev/null 2>&1 || die "missing required tool: $t"
done
command -v say >/dev/null 2>&1 || die "this script needs macOS \`say\` to synthesize the dialogue."

# The token is only ever a local dev token; read it the same way the stack does.
TOKEN="${DEVICE_TOKEN:-}"
if [[ -z "$TOKEN" && -f "$ROOT/.env" ]]; then
  TOKEN="$(grep -E '^DEVICE_TOKEN=' "$ROOT/.env" | head -1 | cut -d= -f2- || true)"
fi
TOKEN="${TOKEN:-dev-secret-token}"

# GUARD: never let this script write into a real deployment. The eval harness applies the same
# rule with `*_test`; ours is `*_demo`.
DB_NAME="${DB_URL##*/}"; DB_NAME="${DB_NAME%%\?*}"
[[ "$DB_NAME" == *_demo ]] || die "refusing to run: DEMO_DB_URL database is '$DB_NAME', which does not end in '_demo'.
       This script injects footage and renames identities; pointing it at a real database
       would mix synthetic demo data into genuine recordings."

psql "$DB_URL" -c 'SELECT 1' >/dev/null 2>&1 || die "cannot connect to $DB_URL — run: createdb $DB_NAME"
curl -fsS -m 5 "$BACKEND/healthz" >/dev/null 2>&1 || die "backend not reachable at $BACKEND (start the stack first — see the header of this script)"

# The stack must be the one pointed at the demo DB, otherwise we'd be feeding a real install.
# Prove it: the demo DB must carry the migrated schema the running backend applied.
psql "$DB_URL" -c 'SELECT 1 FROM segments LIMIT 1' >/dev/null 2>&1 \
  || die "the '$DB_NAME' database has no \`segments\` table, so the running stack is NOT using it.
       Restart the stack with DATABASE_URL=$DB_URL (see the header of this script)."

mkdir -p "$CACHE" "$CLIPDIR"

# ---------------------------------------------------------------------------- optional reset
# DEMO_RESET=1 empties the demo data so a rebuild is coherent rather than layered on top of a
# previous run. Safe only because of the `*_demo` guard above. The stack can stay running:
# TRUNCATE does not need the connections dropped.
if [[ "${DEMO_RESET:-0}" == "1" ]]; then
  log "reset: truncating demo data in $DB_NAME"
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "
    TRUNCATE devices, segments, sessions, streams,
             segment_transcription_status, segment_vision_status,
             transcript_sentences, speakers, speaker_segments,
             persons, person_segments, license_plates, plate_detections,
             scene_objects, events, video_events, alert_rules, alert_deliveries, watchlist,
             conversations, threader_state, rolling_summaries, entity_profiles,
             entity_edges, entity_baselines, entity_journeys, daily_digests, graph_state,
             gotham_pending_actions, chat_sessions, chat_messages, audit_log
      CASCADE;"
  # `graph_state` and `threader_state` are SINGLETONS seeded by migrations 0028 and 0025
  # (`INSERT INTO ... (id) VALUES (1)`). Truncating them makes the worker's graph and threader
  # passes fail forever with "no rows returned by a query that expected to return at least one
  # row", which silently empties the Investigate page. Re-seed them.
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "
    INSERT INTO graph_state    (id) VALUES (1) ON CONFLICT DO NOTHING;
    INSERT INTO threader_state (id) VALUES (1) ON CONFLICT DO NOTHING;"
  rm -rf "$WORK/.feed"
fi

# ---------------------------------------------------------------------------- PD sources
# Reuse the eval clip cache when it is already populated; otherwise fetch from Wikimedia.
fetch() { # name url
  local name="$1" url="$2" dest="$CACHE/$1"
  [[ -s "$dest" ]] && return 0
  if [[ -s "$EVAL_CACHE/$name" ]]; then
    log "reuse  $name (from the eval clip cache)"
    cp "$EVAL_CACHE/$name" "$dest"; return 0
  fi
  log "fetch  $name"
  curl -fSL -m 300 -o "$dest" "$url"
}
fetch face_id.jpg    "https://commons.wikimedia.org/wiki/Special:FilePath/Judith%20A.%20Resnik,%20official%20portrait%20(cropped).jpg"
fetch bob.jpg        "https://commons.wikimedia.org/wiki/Special:FilePath/Sally_Ride_(1984).jpg"
fetch plate_ocr.jpg  "https://commons.wikimedia.org/wiki/Special:FilePath/Cars_in_traffic_in_Auckland,_New_Zealand_-_copyright-free_photo_released_to_public_domain.jpg"

# ---------------------------------------------------------------------------- dialogue
# Scripted household conversation, synthesized with two distinct `say` voices per camera.
# Deliberately mundane and specific: the RAG chat demo needs a question with a real answer
# in the transcript. Nothing here is a credential, an address, or a real person.
say_dialogue() { # out.wav  "voice|line" ...
  local out="$1"; shift
  local tmp="$WORK/.say"; rm -rf "$tmp"; mkdir -p "$tmp"
  local i=0 list="$tmp/list.txt" ; : > "$list"
  for spec in "$@"; do
    local voice="${spec%%|*}" line="${spec#*|}"
    i=$((i+1))
    say -v "$voice" -o "$tmp/$i.aiff" "$line"
    # 0.7s of room between turns, so the ASR sees sentence boundaries rather than one blur.
    ffmpeg -y -loglevel error -f lavfi -i "anullsrc=r=16000:cl=mono" -t 0.7 "$tmp/$i.gap.wav"
    printf "file '%s'\nfile '%s'\n" "$tmp/$i.aiff" "$tmp/$i.gap.wav" >> "$list"
  done
  # loudnorm because a real camera has AGC, and the worker's skip-silent VAD gate drops
  # anything too quiet (the same lesson fetch_eval_clips.sh records).
  ffmpeg -y -loglevel error -f concat -safe 0 -i "$list" \
    -af "loudnorm=I=-20:TP=-3:LRA=11,aresample=16000" -ac 1 "$tmp/joined.wav"
  # Loop the conversation to fill the clip, then pin the exact duration.
  ffmpeg -y -loglevel error -stream_loop -1 -i "$tmp/joined.wav" -t "$CLIP_SECS" \
    -ac 1 -ar 16000 "$out"
  rm -rf "$tmp"
}

log "synthesizing dialogue (${CLIP_SECS}s per camera)"
say_dialogue "$WORK/front_door.wav" \
  "Daniel|Afternoon. I have got a parcel here for number forty one." \
  "Samantha|That is us. Could you leave it inside the porch? The rain is getting in." \
  "Daniel|No problem at all. It does need a signature, if you do not mind." \
  "Samantha|Of course. Is this the one from the garden centre?" \
  "Daniel|It is. There were two boxes. The second one is on tomorrow's round."

say_dialogue "$WORK/driveway.wav" \
  "Daniel|Is that your van blocking the drive?" \
  "Karen|Sorry, that is the roofer. He said he would be finished by four." \
  "Daniel|No rush. Did he give you a quote for the gutters in the end?" \
  "Karen|Eighteen hundred, and that includes the downpipe at the back." \
  "Daniel|That is not bad. Ours came in a fair bit higher than that."

say_dialogue "$WORK/back_garden.wav" \
  "Moira|The fox has been back. It has been at the bins again." \
  "Samantha|Third night running now. I will move them round the side." \
  "Moira|Good idea. The camera should catch it if it comes back tonight." \
  "Samantha|It always turns up just after the light goes off."

# ---------------------------------------------------------------------------- clips
# Ken-burns a still into real video: a slow pan/zoom means every sampled frame contains the
# subject, and consecutive frames differ enough that the motion gate does not treat the clip
# as a static image.
kenburns() { # src.jpg  audio.wav  out.mp4
  local frames=$(( CLIP_SECS * FPS ))
  ffmpeg -y -loglevel error -loop 1 -i "$1" -i "$2" \
    -vf "scale=2560:1440:force_original_aspect_ratio=increase,crop=2560:1440,zoompan=z='min(zoom+0.0004,1.35)':d=${frames}:s=1280x720:fps=${FPS},format=yuv420p" \
    -t "$CLIP_SECS" -map 0:v -map 1:a \
    -c:v libx264 -preset veryfast -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k \
    "$3"
}

# The plate lane runs inside a vehicle ROI, so the crop must keep the WHOLE car with the plate
# still large enough to OCR. Coordinates are for the 5184x3456 public-domain source.
plate_clip() { # src.jpg audio.wav out.mp4
  ffmpeg -y -loglevel error -loop 1 -i "$1" -i "$2" \
    -vf "crop=1100:900:3950:2450,scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,zoompan=z='min(zoom+0.0002,1.12)':d=$(( CLIP_SECS * FPS )):s=1280x720:fps=${FPS},format=yuv420p" \
    -t "$CLIP_SECS" -map 0:v -map 1:a \
    -c:v libx264 -preset veryfast -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k \
    "$3"
}

log "building clips"
kenburns   "$CACHE/face_id.jpg"   "$WORK/front_door.wav"  "$CLIPDIR/front_door.mp4"
plate_clip "$CACHE/plate_ocr.jpg" "$WORK/driveway.wav"    "$CLIPDIR/driveway.mp4"
kenburns   "$CACHE/bob.jpg"       "$WORK/back_garden.wav" "$CLIPDIR/back_garden.mp4"

# ---------------------------------------------------------------------------- inject
# device_id | clip | display name
CAMERAS=(
  "demo-front-door|front_door.mp4|Front Door"
  "demo-driveway|driveway.mp4|Driveway"
  "demo-back-garden|back_garden.mp4|Back Garden"
)
# Hour-of-day for each slot, so footage lands at plausible times rather than all at once.
SLOT_HOURS=(9 17 13 20 11)

api() { # method path [json]
  local m="$1" p="$2"
  if [[ $# -ge 3 ]]; then
    curl -fsS -X "$m" "$BACKEND$p" -H "authorization: Bearer $TOKEN" \
      -H 'content-type: application/json' -d "$3"
  else
    curl -fsS -X "$m" "$BACKEND$p" -H "authorization: Bearer $TOKEN"
  fi
}

total=0
for day in $(seq "$DAYS" -1 1); do
  for slot in $(seq 1 "$SLOTS"); do
    hour="${SLOT_HOURS[$(( (slot - 1) % ${#SLOT_HOURS[@]} ))]}"
    for row in "${CAMERAS[@]}"; do
      IFS='|' read -r dev clip _name <<<"$row"
      # Segment ids are derived from (seed, sequence). Fold the clip's content digest into the
      # seed so regenerating a clip (different length, different dialogue) mints fresh ids
      # instead of re-POSTing existing ids with different bytes — which the backend rejects
      # with 422 exactly as it should.
      clip_sig="$(shasum -a 256 "$CLIPDIR/$clip" | cut -c1-12)"
      # Wall-clock nanoseconds for `day` days ago at `hour`:00, offset per camera so the three
      # cameras do not all start on the same instant (co-presence stays believable).
      start_ns=$(python3 - "$day" "$hour" "$dev" <<'PY'
import sys, datetime, zlib
day, hour, dev = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
base = (datetime.datetime.now().replace(hour=hour, minute=0, second=0, microsecond=0)
        - datetime.timedelta(days=day))
# deterministic 0-25 minute per-camera offset
base += datetime.timedelta(minutes=zlib.crc32(dev.encode()) % 26)
print(int(base.timestamp() * 1_000_000_000))
PY
)
      log "inject $dev  day-$day ${hour}:00  ($clip)"
      python3 "$ROOT/local_dev/feed_segments.py" \
        --url "$BACKEND/v1/segments" \
        --token "$TOKEN" \
        --device "$dev" \
        --video "$CLIPDIR/$clip" \
        --seg-seconds 2 \
        --capture-start-ns "$start_ns" \
        --segment-id-seed "demo-$dev-$day-$slot-$clip_sig" \
        --work-dir "$WORK/.feed/$dev" \
        --state-file "$WORK/.feed/$dev-$day-$slot.json" \
        >/dev/null
      total=$((total+1))
    done
  done
done
log "injected $total clip runs"

# Prove the footage landed in the DEMO database and not somewhere else.
seg_count="$(psql "$DB_URL" -tAc 'SELECT count(*) FROM segments')"
[[ "$seg_count" -gt 0 ]] || die "no segments in $DB_NAME after injection — the running stack is pointed at a different database."
log "segments in $DB_NAME: $seg_count"

# ---------------------------------------------------------------------------- name the cameras
for row in "${CAMERAS[@]}"; do
  IFS='|' read -r dev _clip name <<<"$row"
  api PATCH "/v1/devices/$dev" "$(python3 -c 'import json,sys; print(json.dumps({"display_name": sys.argv[1]}))' "$name")" >/dev/null
  log "named  $dev → $name"
done

# ---------------------------------------------------------------------------- wait for processing
log "waiting for the worker to drain (ASR + embeddings + vision)…"
deadline=$(( $(date +%s) + ${DEMO_DRAIN_TIMEOUT:-3600} ))
while :; do
  read -r a_pend v_pend <<<"$(psql "$DB_URL" -tAF' ' -c "
    SELECT
      (SELECT count(*) FROM segment_transcription_status WHERE status IN ('pending','claimed')),
      (SELECT count(*) FROM segment_vision_status        WHERE status IN ('pending','claimed'))")"
  [[ "${a_pend:-0}" -eq 0 && "${v_pend:-0}" -eq 0 ]] && break
  if (( $(date +%s) > deadline )); then
    log "WARN: drain timed out with audio=$a_pend vision=$v_pend still queued — continuing anyway."
    break
  fi
  printf '\r[demo]   audio queue %-5s vision queue %-5s' "$a_pend" "$v_pend"
  sleep 10
done
printf '\r'
log "processing complete"

# ---------------------------------------------------------------------------- name identities
# The perception lanes mint anonymous clusters; give them fictional names so the People,
# Voices, and Plates screens read like a real install instead of a row of UUIDs.
# Faces and voices get DISJOINT name pools on purpose. The graph proposes voice↔face bindings
# rather than asserting them, and the Investigate entity card surfaces those as "same-identity
# candidate". Naming a voice and a face identically makes that read as a duplicate row instead of
# what it is — "this voice may belong to this face, confidence 0.40, confirm or reject".
PERSON_NAMES=("Dana Whitfield" "Marcus Ellery" "Priya Raman")
SPEAKER_NAMES=("Aoife Brennan" "Tomas Vega" "Nadia Okoye" "Ruth Calder")

name_entities() { # endpoint id_field names...
  local ep="$1" idf="$2"; shift 2
  local names=("$@") i=0
  local ids
  ids="$(api GET "/v1/$ep" | python3 -c "
import json,sys
rows = json.load(sys.stdin)
rows = rows if isinstance(rows, list) else rows.get('$ep', [])
print('\n'.join(str(r['$idf']) for r in rows))" || true)"
  [[ -z "$ids" ]] && { log "no $ep to name (lane produced none)"; return 0; }
  while read -r id; do
    [[ -z "$id" ]] && continue
    local nm="${names[$(( i % ${#names[@]} ))]}"
    api PATCH "/v1/$ep/$id" "$(python3 -c 'import json,sys; print(json.dumps({"display_name": sys.argv[1]}))' "$nm")" >/dev/null || true
    log "named  $ep/$id → $nm"
    i=$((i+1))
  done <<<"$ids"
}

name_entities persons  person_id  "${PERSON_NAMES[@]}"
name_entities speakers speaker_id "${SPEAKER_NAMES[@]}"

# ---------------------------------------------------------------------------- watchlist + rules
# Watch the plate, not a person, so the Watchlist screen has content. `subject_type` accepts
# exactly 'person' or 'plate' (hushai-backend/src/watchlist.rs:119) and the row renders a crop of
# whichever it is (hushai-viewer/ui/js/events/events.js:309). A person row would therefore put a
# face crop on screen — and this demo's faces are public-domain photographs of real, identifiable
# people, which is not something to publish in a screenshot of a surveillance product. See
# docs/screenshots.md.
first_plate="$(api GET /v1/plates | python3 -c "
import json,sys
rows = json.load(sys.stdin); rows = rows if isinstance(rows, list) else rows.get('plates', [])
print(rows[0]['plate_id'] if rows else '')" || true)"
if [[ -n "$first_plate" ]]; then
  api POST /v1/watchlist "$(python3 -c 'import json,sys; print(json.dumps({"subject_type":"plate","subject_id":sys.argv[1],"reason":"Demo: unrecognised vehicle, flagged for follow-up"}))' "$first_plate")" >/dev/null || true
  log "watchlist ← plate $first_plate"
fi

# A couple of plausible alert rules so the Alert rules manager has content. `channels: null`
# keeps them inert — a demo database should not be able to call out to anything.
api POST /v1/alert-rules '{
  "name": "Anyone at the front door after midnight",
  "event_types": ["person_seen"],
  "device_ids": ["demo-front-door"],
  "min_severity": "warning",
  "time_start_minutes": 0,
  "time_end_minutes": 360,
  "cooldown_secs": 900
}' >/dev/null || log "WARN: could not create the front-door alert rule"
api POST /v1/alert-rules '{
  "name": "Unrecognised vehicle on the driveway",
  "event_types": ["plate_seen"],
  "device_ids": ["demo-driveway"],
  "min_severity": "info",
  "cooldown_secs": 1800
}' >/dev/null || log "WARN: could not create the driveway alert rule"
log "alert rules created"

# ---------------------------------------------------------------------------- summary
psql "$DB_URL" -c "
  SELECT 'devices' AS what, count(*) FROM devices
  UNION ALL SELECT 'segments',   count(*) FROM segments
  UNION ALL SELECT 'sentences',  count(*) FROM transcript_sentences
  UNION ALL SELECT 'speakers',   count(*) FROM speakers
  UNION ALL SELECT 'persons',    count(*) FROM persons
  UNION ALL SELECT 'plates',     count(*) FROM license_plates
  UNION ALL SELECT 'objects',    count(*) FROM scene_objects
  UNION ALL SELECT 'events',     count(*) FROM events;"

cat <<EOF

[demo] done. Open the viewer and pick a date within the last $DAYS days:

  http://127.0.0.1:8070/

[demo] To capture the README screenshots from this data:

  cd hushai-viewer/e2e && npm i && node shots.mjs

EOF
