# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: segment.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'segment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsegment.proto\x12\thushai.v1\"\xec\x03\n\x0fSegmentManifest\x12\x12\n\nsegment_id\x18\x01 \x01(\x0c\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x11\n\tstream_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\x0c\x12\x10\n\x08sequence\x18\x05 \x01(\x04\x12\x13\n\x0bsource_kind\x18\x06 \x01(\t\x12(\n\nmedia_type\x18\x07 \x01(\x0e\x32\x14.hushai.v1.MediaType\x12\r\n\x05\x63odec\x18\x08 \x01(\t\x12\x11\n\tcontainer\x18\t \x01(\t\x12\x17\n\x0f\x63odec_init_data\x18\n \x01(\x0c\x12 \n\x18\x63\x61pture_start_unix_nanos\x18\x0b \x01(\x06\x12\x1d\n\x15monotonic_start_nanos\x18\x0c \x01(\x04\x12\x16\n\x0e\x64uration_nanos\x18\r \x01(\x04\x12\x16\n\x0e\x63ontent_sha256\x18\x0e \x01(\x0c\x12\x10\n\x08\x62yte_len\x18\x0f \x01(\x04\x12\x12\n\ngap_before\x18\x10 \x01(\x08\x12\x34\n\x05\x61ttrs\x18\x11 \x03(\x0b\x32%.hushai.v1.SegmentManifest.AttrsEntry\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x12\x10)*H\n\tMediaType\x12\x1a\n\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05\x41UDIO\x10\x01\x12\t\n\x05VIDEO\x10\x02\x12\t\n\x05MUXED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'segment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEGMENTMANIFEST_ATTRSENTRY']._loaded_options = None
  _globals['_SEGMENTMANIFEST_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_MEDIATYPE']._serialized_start=523
  _globals['_MEDIATYPE']._serialized_end=595
  _globals['_SEGMENTMANIFEST']._serialized_start=29
  _globals['_SEGMENTMANIFEST']._serialized_end=521
  _globals['_SEGMENTMANIFEST_ATTRSENTRY']._serialized_start=471
  _globals['_SEGMENTMANIFEST_ATTRSENTRY']._serialized_end=515
# @@protoc_insertion_point(module_scope)
